version: "3.8"
networks:
    backend:
        driver: bridge
services:
  api:
    image: cosmtrek/air
    # working_dir value has to be the same of mapped volume
    working_dir: /go/src/github.com/pajaroturco/go-social-network
    ports:
      - ${PORT}:${PORT}
    volumes:
      - ./backend:/go/src/github.com/pajaroturco/go-social-network
    networks:
      - backend
    depends_on:
      - mongo
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: twitter
    ports:
        - "27017:27017"
    volumes:
        - ../../db/data_mongo:/data/db
    networks:
        - backend